local MODULE = {
    name = "SCP-131",
    author = "Augaton",
    version = "1.1.0",
    description = [[SCP 131 system for players, including compatibility with 173 system.]],
    icon = "icon16/eye.png",
    version_url = "https://raw.githubusercontent.com/Augaton/Augaton-scp131/refs/heads/main/lua/guthscp/modules/scp131/main.lua",
    dependencies = {
        base = "2.4.0",
        guthscp173 = "2.1.0",
        guthscpkeycard = "optional:2.1.6",
    },
    requires = {
        ["shared.lua"] = guthscp.REALMS.SHARED,
        ["server.lua"] = guthscp.REALMS.SERVER,
        ["client.lua"] = guthscp.REALMS.CLIENT,
    },
}

MODULE.menu = {
    config = {
        form = {
            "General",
            {
                {
                    type = "Number",
                    name = "Keycard Level",
                    id = "keycard_level",
                    desc = [[Set a keycard level for SCP-131's swep to open doors.]],
                    default = 3,
                    min = 0,
                    max = function( self, numwang )
                        if self:is_disabled() then return 0 end
                        return guthscp.modules.guthscpkeycard.max_keycard_level
                    end,
                    is_disabled = function( self, numwang )
                        return guthscp.modules.guthscpkeycard == nil
                    end,
                },
                {
                    type = "Bool",
                    name = "Immortal",
                    id = "scp131_immortal",
                    desc = "If checked, the player as SCP-131 can't take damage.",
                    default = true,
                },
                {
                    type = "Bool",
                    name = "Harmless",
                    id = "harmless",
                    desc = "If checked, SCP-131 can't deal damage to anyone (it is a Safe-class object).",
                    default = true,
                },
                {
                    type = "Number",
                    name = "Walk Speed",
                    id = "walk_speed",
                    desc = "Walking speed of the player. Only used when the wheel movement is disabled.",
                    default = 160,
                    min = 1,
                },
                {
                    type = "Number",
                    name = "Run Speed",
                    id = "run_speed",
                    desc = "Running speed of the player. Only used when the wheel movement is disabled.",
                    default = 350,
                    min = 1,
                },
            },
            "Wheel",
            {
                {
                    type = "Bool",
                    name = "Enable Wheel Movement",
                    id = "wheel_enabled",
                    desc = "SCP-131 rolls on a wheel: it takes time to reach its top speed and, having no brakes, it keeps rolling when the player stops pressing a direction.",
                    default = true,
                },
                {
                    type = "Number",
                    name = "Top Speed",
                    id = "wheel_max_speed",
                    desc = "Maximum rolling speed, in hammer units per second (the article describes 60m covered in a matter of seconds).",
                    default = 600,
                    min = 50,
                },
                {
                    type = "Number",
                    name = "Acceleration",
                    id = "wheel_acceleration",
                    desc = "How many units per second are gained each second while rolling.",
                    default = 420,
                    min = 10,
                },
                {
                    type = "Number",
                    name = "Coasting Deceleration",
                    id = "wheel_coast_deceleration",
                    desc = "How many units per second are lost each second when no direction is pressed. Keep it low: SCP-131 has no braking system.",
                    default = 110,
                    min = 0,
                },
                {
                    type = "Number",
                    name = "Turn Rate",
                    id = "wheel_turn_rate",
                    desc = "How fast the wheel can change direction. Higher is more agile.",
                    default = 6,
                    min = 0.5,
                    decimals = 1,
                },
                {
                    type = "Number",
                    name = "Grip At Top Speed",
                    id = "wheel_grip_min",
                    desc = "Fraction of the turn rate still available at top speed (1 = turns as well as when standing still).",
                    default = 0.3,
                    min = 0.05,
                    max = 1,
                    decimals = 2,
                },
                {
                    type = "Bool",
                    name = "Enable Crashes",
                    id = "crash_enabled",
                    desc = "Having no brakes, SCP-131 stuns itself when it rolls into a wall at high speed.",
                    default = true,
                },
                {
                    type = "Number",
                    name = "Crash Speed",
                    id = "crash_min_speed",
                    desc = "Minimum speed required to crash into a wall.",
                    default = 350,
                    min = 50,
                },
                {
                    type = "Number",
                    name = "Crash Stun Duration",
                    id = "crash_stun_time",
                    desc = "How long SCP-131 stays dizzy after a crash, in seconds. It can't move, roll or hold SCP-173 while dizzy.",
                    default = 1.5,
                    min = 0,
                    decimals = 1,
                },
            },
            "Climbing",
            {
                {
                    type = "Bool",
                    name = "Enable Climbing",
                    id = "climb_enabled",
                    desc = "SCP-131 climbs sheer surfaces: hold the jump key while facing a wall.",
                    default = true,
                },
                {
                    type = "Number",
                    name = "Climbing Speed",
                    id = "climb_speed",
                    desc = "Vertical speed while climbing, in hammer units per second.",
                    default = 120,
                    min = 10,
                },
                {
                    type = "Number",
                    name = "Climbing Reach",
                    id = "climb_reach",
                    desc = "Maximum distance to a wall to be able to climb it.",
                    default = 24,
                    min = 4,
                },
                {
                    type = "Number",
                    name = "Climbing Duration",
                    id = "climb_max_time",
                    desc = "Maximum climbing time before SCP-131 has to touch the ground again, in seconds (0 = unlimited).",
                    default = 6,
                    min = 0,
                    decimals = 1,
                },
            },
            "Bonding",
            {
                {
                    type = "Bool",
                    name = "Enable Bonding",
                    id = "bond_enabled",
                    desc = "SCP-131 can bond with a player showing it affection, and then follows him around like a puppy.",
                    default = true,
                },
                {
                    type = "Number",
                    name = "Bonding Duration",
                    id = "bond_time",
                    desc = "How long the secondary attack must be held on a player to bond with him, in seconds.",
                    default = 2.5,
                    min = 0.5,
                    decimals = 1,
                },
                {
                    type = "Number",
                    name = "Bonding Range",
                    id = "bond_range",
                    desc = "Maximum distance to a player to bond with him.",
                    default = 150,
                    min = 32,
                },
                {
                    type = "Number",
                    name = "Attention Timeout",
                    id = "bond_timeout",
                    desc = "If its companion doesn't look at it for this long, SCP-131 loses interest and the bond breaks, in seconds (0 = never).",
                    default = 240,
                    min = 0,
                },
                {
                    type = "Number",
                    name = "Attention Distance",
                    id = "bond_attention_distance",
                    desc = "Maximum distance at which a look from the companion counts as attention.",
                    default = 400,
                    min = 32,
                },
            },
            "SCP-173",
            {
                {
                    type = "Number",
                    name = "Warden Range",
                    id = "guard_distance",
                    desc = "Maximum distance at which SCP-131 can hold SCP-173 with its unblinking eye (0 = unlimited).",
                    default = 1200,
                    min = 0,
                },
                {
                    type = "Bool",
                    name = "Enable Tumbling",
                    id = "tumble_enabled",
                    desc = "Since SCP-131 can't be killed, damages send it rolling away instead: it loses eye contact for a few seconds. This is the only counterplay SCP-173 has against a warden.",
                    default = true,
                },
                {
                    type = "Number",
                    name = "Tumbling Force",
                    id = "tumble_force",
                    desc = "Horizontal force applied to SCP-131 when it is sent tumbling.",
                    default = 350,
                    min = 0,
                },
                {
                    type = "Number",
                    name = "Tumbling Lift",
                    id = "tumble_lift",
                    desc = "Vertical force applied to SCP-131 when it is sent tumbling.",
                    default = 150,
                    min = 0,
                },
                {
                    type = "Number",
                    name = "Tumbling Stun Duration",
                    id = "tumble_stun_time",
                    desc = "How long SCP-131 stays dizzy after being sent tumbling, in seconds.",
                    default = 2.5,
                    min = 0,
                    decimals = 1,
                },
                {
                    type = "Number",
                    name = "Tumbling Cooldown",
                    id = "tumble_cooldown",
                    desc = "Minimum delay between two tumbles, in seconds. Prevents automatic weapons from locking SCP-131 on the floor.",
                    default = 4,
                    min = 0,
                    decimals = 1,
                },
            },
            "SCP-131-A & SCP-131-B",
            {
                {
                    type = "Color",
                    name = "SCP-131-A Color",
                    id = "color_a",
                    desc = "Body color of the first Eye Pod (burnt orange).",
                    default = Color( 204, 85, 0 ),
                },
                {
                    type = "Color",
                    name = "SCP-131-B Color",
                    id = "color_b",
                    desc = "Body color of the second Eye Pod (mustard yellow).",
                    default = Color( 227, 192, 60 ),
                },
                {
                    type = "Number",
                    name = "Swarm Distance",
                    id = "swarm_distance",
                    desc = "Distance under which both Eye Pods encourage each other (0 = disabled).",
                    default = 200,
                    min = 0,
                },
                {
                    type = "Number",
                    name = "Swarm Speed Bonus",
                    id = "swarm_speed_bonus",
                    desc = "Top speed bonus while both Eye Pods roll together, in percent.",
                    default = 15,
                    min = 0,
                },
            },
            "Sounds",
            {
                {
                    type = "String[]",
                    name = "Chirp",
                    id = "chirp_sounds",
                    desc = "Sounds randomly played on the primary attack. This addon ships no sound file: add your own paths, relative to the 'sound/' folder. Remove all elements to disable chirping.",
                    default = {},
                },
                {
                    type = "String[]",
                    name = "Distress",
                    id = "distress_sounds",
                    desc = "Sounds randomly played when SCP-131 is sent tumbling. Falls back to the chirp sounds when empty.",
                    default = {},
                },
                {
                    type = "String[]",
                    name = "Crash",
                    id = "crash_sounds",
                    desc = "Sounds randomly played when SCP-131 rolls into a wall. Falls back to the distress sounds when empty.",
                    default = {},
                },
                {
                    type = "Number",
                    name = "Chirp Cooldown",
                    id = "chirp_cooldown",
                    desc = "Delay between two chirps, in seconds.",
                    default = 1.5,
                    min = 0.1,
                    decimals = 1,
                },
                {
                    type = "Number",
                    name = "Hear Distance",
                    id = "sound_hear_distance",
                    desc = "Distance at which the sounds of SCP-131 can be heard.",
                    default = 500,
                    min = 0,
                },
                {
                    type = "Number",
                    name = "Volume",
                    id = "sound_volume",
                    desc = "Volume of the sounds of SCP-131.",
                    default = 1,
                    min = 0,
                    max = 1,
                    decimals = 2,
                },
            },
        },
    },
    details = {
        {
            text = "CC-BY-SA",
            icon = "icon16/page_white_key.png",
        },
        "Social",
        {
            text = "Github",
            icon = "guthscp/icons/github.png",
            url = "https://github.com/Augaton/Augaton-scp131",
        },
        {
            text = "Discord",
            icon = "guthscp/icons/discord.png",
            url = "https://discord.gg/kJFQe95pgh",
        },
    },
}

function MODULE:init()
    self:info( "SCP-131 Player Module loaded." )
end

guthscp.module.hot_reload( "scp131" )
return MODULE
